# Generated by Django 3.2.3 on 2021-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('proce', models.CharField(max_length=100, null=True, verbose_name='Precio del producto')),
                ('picture', models.URLField(null=True, verbose_name='Url de la previsualizacion del producto')),
                ('origin', models.URLField(null=True, verbose_name='url del producto')),
                ('date', models.DateField()),
            ],
        ),
    ]
